-- generated by grok ai https://grok.com/chat/a11f34fd-a36b-491a-bd5c-46fa206ffca8 
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- Table structure for table `unit`
CREATE TABLE `unit` (
    `kode_unit` VARCHAR(10) NOT NULL PRIMARY KEY,
    `parent_unit` VARCHAR(100),
    `nama_unit` VARCHAR(100) NOT NULL,
    `nama_singkat` VARCHAR(50),
    `jenjang_pendidikan` VARCHAR(50),
    `level` INT,
    `alamat` VARCHAR(255),
    `telepon` VARCHAR(50),
    `akreditasi` VARCHAR(10),
    `sk_akreditasi` VARCHAR(100),
    `kode\application_id` VARCHAR(50),
    `gelar` VARCHAR(50),
    `ketua` VARCHAR(100),
    `website` VARCHAR(255),
    `is_active` TINYINT(1) NOT NULL DEFAULT '1',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `pegawai`
CREATE TABLE `pegawai` (
    `nip` VARCHAR(50) NOT NULL PRIMARY KEY,
    `nama` VARCHAR(100) NOT NULL,
    `hombase` VARCHAR(100) REFERENCES `unit`(`kode_unit`),
    `jenis_kelamin` CHAR(1) NOT NULL,
    `tempat_lahir` VARCHAR(50),
    `tanggal_lahir` DATE,
    `agama` VARCHAR(50),
    `nidn` CHAR(10) UNIQUE,
    `gelar_depan` VARCHAR(10),
    `gelar_belakang` VARCHAR(100),
    `golonganpangkat` VARCHAR(50),
    `jabatan_fungsional` VARCHAR(100),
    `jabatan_struktural` VARCHAR(100),
    `alamat_rumah` VARCHAR(255),
    `no__telepon` VARCHAR(50),
    `email_pribadi` VARCHAR(100),
    `email_kampus` VARCHAR(255) UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `mahasiswa`
CREATE TABLE `mahasiswa` (
    `nim` VARCHAR(10) NOT NULL PRIMARY KEY,
    `periode_masuk` VARCHAR(50) NOT NULL,
    `program_studi` VARCHAR(100) NOT NULL REFERENCES `unit`(`kode_unit`),
    `nama` VARCHAR(100) NOT NULL,
    `sistem_kuliah` VARCHAR(50),
    `jalur_penerimaan` VARCHAR(50),
    `gelombang_daftar` VARCHAR(50),
    `transfer__tidak` VARCHAR(10),
    `universitas_asal` VARCHAR(100),
    `nim_asal` VARCHAR(50),
    `ipk_asal` DECIMAL(10,2),
    `kurikulum` VARCHAR(10),
    `agama` VARCHAR(50),
    `kewarganegaraan` VARCHAR(50),
    `status_mahasiswa` VARCHAR(50) NOT NULL,
    `alamat` TEXT,
    `telepon` VARCHAR(50),
    `hp` VARCHAR(50),
    `tempat_lahir` VARCHAR(100),
    `tgl__lahir` DATE,
    `kodepos` VARCHAR(10),
    `jenis_kelamin` CHAR(1) NOT NULL,
    `golongan_darah` VARCHAR(10),
    `status_nikah` VARCHAR(10),
    `email` VARCHAR(255) UNIQUE,
    `no__ktpnik` VARCHAR(50) UNIQUE,
    `no__kk` VARCHAR(50),
    `rt` VARCHAR(10),
    `rw` VARCHAR(10),
    `dusun` VARCHAR(50),
    `desakelurahan` VARCHAR(100),
    `kecamatan` VARCHAR(100),
    `kota` VARCHAR(100),
    `propinsi` VARCHAR(100),
    `tgl__daftar` DATE,
    `nama_ayah` VARCHAR(100),
    `alamat_ayah` VARCHAR(255),
    `telp__ayah` VARCHAR(50),
    `tgl__lahir_ayah` DATE,
    `pendidikan_ayah` VARCHAR(50),
    `pekerjaan_ayah` VARCHAR(50),
    `penghasilan_ayah` VARCHAR(10),
    `nama_ibu` VARCHAR(100),
    `alamat_ibu` VARCHAR(255),
    `telp__ibu` VARCHAR(50),
    `tgl__lahir_ibu` DATE,
    `pendidikan_ibu` VARCHAR(50),
    `pekerjaan_ibu` VARCHAR(50),
    `penghasilan_ibu` VARCHAR(10),
    `nama_wali` VARCHAR(100),
    `alamat_wali` VARCHAR(255),
    `telp__wali` VARCHAR(50),
    `tgl__wali` DATE,
    `pendidikan_wali` VARCHAR(50),
    `pekerjaan_wali` VARCHAR(100),
    `penghasilan_wali` VARCHAR(50),
    `registration_id` BIGINT(20) UNSIGNED DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (`registration_id`) REFERENCES `registrations`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `mahasiswakm`
CREATE TABLE `mahasiswakm` (
    `nim` VARCHAR(50) NOT NULL PRIMARY KEY,
    `periode_masuk` VARCHAR(10) NOT NULL,
    `perguruan_tinggi_asal` VARCHAR(100),
    `program_studi_asal` VARCHAR(100),
    `nama` VARCHAR(100) NOT NULL,
    `jenis_kelamin` CHAR(1) NOT NULL,
    `tempat_lahir` VARCHAR(100),
    `tanggal_lahir` DATE,
    `no__hp` VARCHAR(50),
    `email` VARCHAR(255) UNIQUE,
    `alamat` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `provinces`
CREATE TABLE `provinces` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `cities`
CREATE TABLE `cities` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `province_id` INT(11) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`province_id`) REFERENCES `provinces`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `schools`
CREATE TABLE `schools` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `npsn` VARCHAR(20) UNIQUE,
    `name` VARCHAR(255) NOT NULL,
    `type` ENUM('SMA','SMK','MA','LAINNYA') NOT NULL,
    `province_id` INT(11) NOT NULL,
    `city_id` INT(11) NOT NULL,
    `is_verified` TINYINT(1) NOT NULL DEFAULT '0',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`province_id`) REFERENCES `provinces`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`city_id`) REFERENCES `cities`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `admission_paths`
CREATE TABLE `admission_paths` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(50) NOT NULL UNIQUE,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `registration_fee` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
    `study_system` VARCHAR(50),
    `target_students` TEXT,
    `schedule` VARCHAR(100),
    `start_date` DATE NOT NULL,
    `end_date` DATE NOT NULL,
    `wave` VARCHAR(50),
    `academic_year` VARCHAR(10) NOT NULL,
    `semester` ENUM('GANJIL','GENAP') NOT NULL,
    `is_active` TINYINT(1) NOT NULL DEFAULT '1',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `admission_path_programs`
CREATE TABLE `admission_path_programs` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `admission_path_id` BIGINT(20) UNSIGNED NOT NULL,
    `program_studi` VARCHAR(100) NOT NULL,
    `quota` INT(11) NOT NULL DEFAULT '0',
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `adm_path_prog_unique` (`admission_path_id`,`program_studi`),
    FOREIGN KEY (`admission_path_id`) REFERENCES `admission_paths`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`program_studi`) REFERENCES `unit`(`kode_unit`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `admission_requirements`
CREATE TABLE `admission_requirements` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `admission_path_id` BIGINT(20) UNSIGNED NOT NULL,
    `requirement_name` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `is_mandatory` TINYINT(1) NOT NULL DEFAULT '1',
    `file_type` VARCHAR(50),
    `max_file_size` INT(11) NOT NULL DEFAULT '2048' COMMENT 'dalam KB',
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`admission_path_id`) REFERENCES `admission_paths`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `announcements`
CREATE TABLE `announcements` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `content` TEXT NOT NULL,
    `type` ENUM('INFORMASI','PENGUMUMAN','BEASISWA') NOT NULL,
    `banner_image` VARCHAR(500),
    `is_published` TINYINT(1) NOT NULL DEFAULT '0',
    `publish_date` TIMESTAMP NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `registrations`
CREATE TABLE `registrations` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `registration_number` VARCHAR(50) NOT NULL UNIQUE,
    `admission_path_id` BIGINT(20) UNSIGNED NOT NULL,
    `full_name` VARCHAR(255) NOT NULL,
    `gender` ENUM('MALE','FEMALE') NOT NULL,
    `mobile_number` VARCHAR(20) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `date_of_birth` DATE NOT NULL,
    `place_of_birth` VARCHAR(100) NOT NULL,
    `nationality` VARCHAR(50) NOT NULL DEFAULT 'Indonesia',
    `nik` VARCHAR(20) NOT NULL UNIQUE,
    `province_id` INT(11) NOT NULL,
    `city_id` INT(11) NOT NULL,
    `school_id` BIGINT(20) UNSIGNED NOT NULL,
    `school_specialization` VARCHAR(100) NOT NULL,
    `graduation_year` YEAR(4) NOT NULL,
    `first_choice_program_id` VARCHAR(100) NOT NULL,
    `second_choice_program_id` VARCHAR(100) DEFAULT NULL,
    `registration_status` ENUM('DRAFT','SUBMITTED','VERIFIED','ACCEPTED','REJECTED') NOT NULL DEFAULT 'DRAFT',
    `payment_status` ENUM('PENDING','PAID','FAILED') NOT NULL DEFAULT 'PENDING',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`admission_path_id`) REFERENCES `admission_paths`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`province_id`) REFERENCES `provinces`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`city_id`) REFERENCES `cities`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`school_id`) REFERENCES `schools`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`first_choice_program_id`) REFERENCES `unit`(`kode_unit`) ON DELETE CASCADE,
    FOREIGN KEY (`second_choice_program_id`) REFERENCES `unit`(`kode_unit`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `registration_documents`
CREATE TABLE `registration_documents` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `registration_id` BIGINT(20) UNSIGNED NOT NULL,
    `requirement_id` BIGINT(20) UNSIGNED NOT NULL,
    `file_name` VARCHAR(255) NOT NULL,
    `file_path` VARCHAR(500) NOT NULL,
    `file_size` INT(11) NOT NULL COMMENT 'dalam bytes',
    `upload_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `verification_status` ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
    `verification_notes` TEXT,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`registration_id`) REFERENCES `registrations`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`requirement_id`) REFERENCES `admission_requirements`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `payments`
CREATE TABLE `payments` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `registration_id` BIGINT(20) UNSIGNED NOT NULL,
    `payment_code` VARCHAR(50) NOT NULL UNIQUE,
    `amount` DECIMAL(10,2) NOT NULL,
    `payment_method` VARCHAR(50),
    `payment_date` TIMESTAMP NULL DEFAULT NULL,
    `payment_status` ENUM('PENDING','SUCCESS','FAILED','EXPIRED') NOT NULL DEFAULT 'PENDING',
    `payment_proof` VARCHAR(500),
    `verification_date` TIMESTAMP NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`registration_id`) REFERENCES `registrations`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `users`
CREATE TABLE `users` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(50) NOT NULL UNIQUE,
    `email` VARCHAR(100) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `two_factor_secret` TEXT,
    `two_factor_recovery_codes` TEXT,
    `two_factor_confirmed_at` TIMESTAMP NULL DEFAULT NULL,
    `role` ENUM('SUPER_ADMIN','ADMIN','OPERATOR','VERIFIER','STUDENT') NOT NULL,
    `nip` VARCHAR(50) DEFAULT NULL,
    `nim` VARCHAR(10) DEFAULT NULL,
    `is_active` TINYINT(1) NOT NULL DEFAULT '1',
    `last_login` TIMESTAMP NULL DEFAULT NULL,
    `remember_token` VARCHAR(100),
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`nip`) REFERENCES `pegawai`(`nip`) ON DELETE SET NULL,
    FOREIGN KEY (`nim`) REFERENCES `mahasiswa`(`nim`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `kurikulummk`
CREATE TABLE `kurikulummk` (
    `program_studi` VARCHAR(100) NOT NULL,
    `kurikulum_` VARCHAR(10) NOT NULL,
    `kode_matakuliah` VARCHAR(10) NOT NULL,
    `nama_matakuliah` VARCHAR(100) NOT NULL,
    `semester_matakuliah` INT,
    `sks_matakuliah` INT NOT NULL,
    `sks_tatap_muka` INT,
    `sks_praktikum` INT,
    `sks_simulasi` INT,
    `sks_prактikum_lapangan` INT,
    `nilai_lulus_minimal` DECIMAL(10,2),
    `kelompok_matakuliah` VARCHAR(50),
    `jenis_matakuliah` VARCHAR(50),
    PRIMARY KEY (`program_studi`, `kurikulum_`, `kode_matakuliah`),
    FOREIGN KEY (`program_studi`) REFERENCES `unit`(`kode_unit`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `kelas`
CREATE TABLE `kelas` (
    `program_studi` VARCHAR(100) NOT NULL,
    `tahun_kurikulum` INT NOT NULL,
    `kode_mata_kuliah` VARCHAR(10) NOT NULL,
    `periode` VARCHAR100) NOT NULL,
    `nama_kelas` VARCHAR(10) NOT NULL,
    `hari_1` INT,
    `jam_mulai_1` TIME,
    `jam_selesai_1` TIME,
    `hari_2` VARCHAR(10),
    `jam_mulai_2` TIME,
    `jam_selesai_2` TIME,
    `hari_3` VARCHAR(10),
    `jam_mulai_3` TIME,
    `jam_selesai_3` TIME,
    `hari_4` VARCHAR(10),
    `jam_mulai_4` TIME,
    `jam_selesai_4` TIME,
    `daya_tampung` INT,
    `nip_dosen_1` VARCHAR(10),
    `nama_dosen_1` VARCHAR(100),
    `nip_dosen_2` CHAR(10),
    `nama_dosen_2` VARCHAR(100),
    PRIMARY KEY (`program_studi`, `tahun_kurikulum`, `kode_mata_kuliah`, `periode`, `nama_kelas`),
    FOREIGN KEY (`program_studi`, `tahun_kurikulum`, `kode_mata_kuliah`) 
        REFERENCES `kurikulummk`(`program_studi`, `kurikulum_`, `kode_matakuliah`),
    FOREIGN KEY (`nip_dosen_1`) REFERENCES `pegawai`(`nip`),
    FOREIGN KEY (`nip_dosen_2`) REFERENCES `pegawai`(`nip`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `kelaskm`
CREATE TABLE `kelaskm` (
    `program_studi_pengampu` VARCHAR(100) NOT NULL,
    `tahun_kurikulum` VARCHAR(10) NOT NULL,
    `kode_mata_kuliah` VARCHAR(10) NOT NULL,
    `periode` VARCHAR(10) NOT NULL,
    `nama_kelas` VARCHAR(50) NOT NULL,
    `hari_1` VARCHAR(10),
    `jam_mulai_1` TIME,
    `jam_selesai_1` TIME,
    `hari_2` VARCHAR(10),
    `jam_mulai_2` TIME,
    `jam_selesai_2` TIME,
    `hari_3` VARCHAR(10),
    `jam_mulai_3` TIME,
    `jam_selesai_3` TIME,
    `hari_4` VARCHAR(10),
    `jam_mulai_4` TIME,
    `jam_selesai_4` TIME,
    `daya_tampung` INT,
    `nip_dosen_1` VARCHAR(50),
    `nama_dosen_1` VARCHAR(100),
    `nip_dosen_2` VARCHAR(50),
    `nama_dosen_2` VARCHAR(100),
    PRIMARY KEY (`program_studi_pengampu`, `tahun_kurikulum`, `kode_mata_kuliah`, `periode`, `nama_kelas`),
    FOREIGN KEY (`program_studi_pengampu`) REFERENCES `unit`(`kode_unit`),
    FOREIGN KEY (`nip_dosen_1`) REFERENCES `pegawai`(`nip`),
    FOREIGN KEY (`nip_dosen_2`) REFERENCES `pegawai`(`nip`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `krs`
CREATE TABLE `krs` (
    `periode` VARCHAR(50) NOT NULL,
    `program_studi_pengampu` VARCHAR(100) NOT NULL,
    `kurikulum` VARCHAR(10) NOT NULL,
    `kode_matakuliah` VARCHAR(10) NOT NULL,
    `nama_matakuliah` VARCHAR(100),
    `nama_kelas` VARCHAR(10) NOT NULL,
    `nim` VARCHAR(10) NOT NULL,
    `nilai_akhir` DECIMAL(10,2),
    `nilai_mutu` DECIMAL(10,2),
    `nilai_huruf` CHAR(1),
    PRIMARY KEY (`periode`, `program_studi_pengampu`, `kurikulum`, `kode_matakuliah`, `nama_kelas`, `nim`),
    FOREIGN KEY (`program_studi_pengampu`, `kurikulum`, `kode_matakuliah`) 
        REFERENCES `kurikulummk`(`program_studi`, `kurikulum_`, `kode_matakuliah`),
    FOREIGN KEY (`nim`) REFERENCES `mahasiswa`(`nim`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `krskm`
CREATE TABLE `krskm` (
    `periode` VARCHAR(10) NOT NULL,
    `program_studi_pengampu` VARCHAR(100) NOT NULL,
    `kurikulum` VARCHAR(50) NOT NULL,
    `kode_matakuliah` VARCHAR(50) NOT NULL,
    `nama_matakuliah` VARCHAR(100),
    `nama_kelas` VARCHAR(50) NOT NULL,
    `perguruan_tinggi_asal` VARCHAR(100),
    `program_studi_asal` VARCHAR(100),
    `nim` VARCHAR(50) NOT NULL,
    `nilai_akhir` DECIMAL(10,2),
    `nilai_mutu` DECIMAL(10,2),
    `nilai_huruf` VARCHAR(10),
    PRIMARY KEY (`periode`, `program_studi_pengampu`, `kurikulum`, `kode_matakuliah`, `nama_kelas`, `nim`),
    FOREIGN KEY (`program_studi_pengampu`) REFERENCES `unit`(`kode_unit`),
    FOREIGN KEY (`nim`) REFERENCES `mahasiswakm`(`nim`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `nilaipindahan`
CREATE TABLE `nilaipindahan` (
    `program_studi` VARCHAR(100) NOT NULL,
    `nim` VARCHAR(10) NOT NULL,
    `kode_matakuliah_asal` VARCHAR(50) NOT NULL,
    `nama_matakuliah_asal` VARCHAR(100),
    `sks_matakuliah_asal` DECIMAL(10,2),
    `nilai_huruf_matakuliah_asal` VARCHAR(10),
    `program_studi_pengampu_matakuliah_diakui` VARCHAR(100),
    `kurikulum_matakuliah_diakui` VARCHAR(10),
    `kode_matakuliah_diakui` VARCHAR(10),
    `nama_matakuliah_diakui` VARCHAR(100),
    `sks_matakuliah_diakui` INT,
    `nilai_huruf_matakuliah_diakui` CHAR(1),
    `nilai_angka_matakuliah_diakui` DECIMAL(10,2),
    PRIMARY KEY (`program_studi`, `nim`, `kode_matakuliah_asal`),
    FOREIGN KEY (`program_studi`) REFERENCES `unit`(`kode_unit`),
    FOREIGN KEY (`nim`) REFERENCES `mahasiswa`(`nim`),
    FOREIGN KEY (`program_studi_pengampu_matakuliah_diakui`) REFERENCES `unit`(`kode_unit`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `perwalian`
CREATE TABLE `perwalian` (
    `periode` VARCHAR(50) NOT NULL,
    `nim` VARCHAR(10) NOT NULL,
    `nama` VARCHAR(100),
    `prodi` VARCHAR(100),
    `periode_masuk` VARCHAR(50),
    `dosen_pembimbing_akademik` VARCHAR(100),
    `sks_lulus` INT,
    `ips` DECIMAL(10,2),
    `ipk` DECIMAL(10,2),
    `ipk_lulus` DECIMAL(10,2),
    PRIMARY KEY (`periode`, `nim`),
    FOREIGN KEY (`nim`) REFERENCES `mahasiswa`(`nim`),
    FOREIGN KEY (`prodi`) REFERENCES `unit`(`kode_unit`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `proporsinilai`
CREATE TABLE `proporsinilai` (
    `periode` VARCHAR(50) NOT NULL,
    `program_studi` VARCHAR(100) NOT NULL,
    `kurikulum` VARCHAR(10) NOT NULL,
    `kode_matakuliah` VARCHAR(10) NOT NULL,
    `nama_matakuliah` VARCHAR(100),
    `nama_kelas` VARCHAR(10) NOT NULL,
    `nim` VARCHAR(10) NOT NULL,
    `komposisi_nilai` VARCHAR(50) NOT NULL,
    `nilai` DECIMAL(10,2),
    PRIMARY KEY (`periode`, `program_studi`, `kurikulum`, `kode_matakuliah`, `nama_kelas`, `nim`, `komposisi_nilai`),
    FOREIGN KEY (`periode`, `program_studi`, `kurikulum`, `kode_matakuliah`, `nama_kelas`, `nim`)
        REFERENCES `krs`(`periode`, `program_studi_pengampu`, `kurikulum`, `kode_matakuliah`, `nama_kelas`, `nim`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `skalanilai`
CREATE TABLE `skalanilai` (
    `kurikulum` VARCHAR(10) NOT NULL,
    `jenjang` VARCHAR(50) NOT NULL,
    `unit` VARCHAR(100) NOT NULL,
    `nilai_angka` DECIMAL(10,2) NOT NULL,
    `nilai_huruf` CHAR(1) NOT NULL,
    `batas_bawah` DECIMAL(10,2) NOT NULL,
    `batas_atas` DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (`kurikulum`, `jenjang`, `unit`, `nilai_huruf`),
    FOREIGN KEY (`unit`) REFERENCES `unit`(`kode_unit`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `skripsi`
CREATE TABLE `skripsi` (
    `nim` VARCHAR(10) NOT NULL PRIMARY KEY,
    `nama` VARCHAR(100),
    `judul` TEXT,
    `status` VARCHAR(10),
    FOREIGN KEY (`nim`) REFERENCES `mahasiswa`(`nim`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `tagihan`
CREATE TABLE `tagihan` (
    `kode_tagihan` VARCHAR(50) NOT NULL PRIMARY KEY,
    `nim` VARCHAR(10) NOT NULL,
    `nama` VARCHAR(100),
    `jenis_cicilan` VARCHAR(10),
    `bulan` VARCHAR(10),
    `potongan` DECIMAL(10,2),
    `denda` DECIMAL(10,2),
    `nominal` DECIMAL(10,2) NOT NULL,
    `nominal_bayar` DECIMAL(10,2),
    `status_lunas` VARCHAR(50),
    FOREIGN KEY (`nim`) REFERENCES `mahasiswa`(`nim`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `tarif`
CREATE TABLE `tarif` (
    `periode_masuk` VARCHAR(50) NOT NULL,
    `gelombang` VARCHAR(50) NOT NULL,
    `jalur_pendaftaran` VARCHAR(50) NOT NULL,
    `sistem_kuliah` VARCHAR(50) NOT NULL,
    `jenis_akun` VARCHAR(50) NOT NULL,
    `nominal` DECIMAL(10,2) NOT NULL,
    `cicilan` INT,
    `denda` DECIMAL(10,2),
    PRIMARY KEY (`periode_masuk`, `gelombang`, `jalur_pendaftaran`, `sistem_kuliah`, `jenis_akun`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `lulusan`
CREATE TABLE `lulusan` (
    `periode_yudisium_` VARCHAR(50) NOT NULL,
    `program_studi` VARCHAR(100) NOT NULL,
    `nim` VARCHAR(10) NOT NULL PRIMARY KEY,
    `no__sk_yudisium` VARCHAR(100),
    `tgl_sk_yudisium` DATE,
    `no__ijazah` VARCHAR(100),
    `tgl_ijazah` DATE,
    `no__transkrip` VARCHAR(50),
    `tgl_transkrip` DATE,
    `judul_skripsi` TEXT,
    FOREIGN KEY (`program_studi`) REFERENCES `unit`(`kode_unit`),
    FOREIGN KEY (`nim`) REFERENCES `mahasiswa`(`nim`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `yudisium`
CREATE TABLE `yudisium` (
    `periode_yudisium` VARCHAR(50) NOT NULL,
    `nim` VARCHAR(10) NOT NULL PRIMARY KEY,
    `nama` VARCHAR(100),
    `prodi` VARCHAR(100),
    `periode_masuk` VARCHAR(50),
    `sks_lulus` INT,
    `ipk_lulus` DECIMAL(10,2),
    `tgl_sk_yudisium` DATE,
    `nomer_sk_yudisium` VARCHAR(100),
    `pin` VARCHAR(100),
    FOREIGN KEY (`nim`) REFERENCES `mahasiswa`(`nim`),
    FOREIGN KEY (`prodi`) REFERENCES `unit`(`kode_unit`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Optional Laravel-specific tables (include only if the academic system uses Laravel)
-- Table structure for table `cache`
CREATE TABLE `cache` (
    `key` VARCHAR(255) NOT NULL,
    `value` MEDIUMTEXT NOT NULL,
    `expiration` INT(11) NOT NULL,
    PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `cache_locks`
CREATE TABLE `cache_locks` (
    `key` VARCHAR(255) NOT NULL,
    `owner` VARCHAR(255) NOT NULL,
    `expiration` INT(11) NOT NULL,
    PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `failed_jobs`
CREATE TABLE `failed_jobs` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(255) NOT NULL UNIQUE,
    `connection` TEXT NOT NULL,
    `queue` TEXT NOT NULL,
    `payload` LONGTEXT NOT NULL,
    `exception` LONGTEXT NOT NULL,
    `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `jobs`
CREATE TABLE `jobs` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `queue` VARCHAR(255) NOT NULL,
    `payload` LONGTEXT NOT NULL,
    `attempts` TINYINT(3) UNSIGNED NOT NULL,
    `reserved_at` INT(10) UNSIGNED DEFAULT NULL,
    `available_at` INT(10) UNSIGNED NOT NULL,
    `created_at` INT(10) UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    KEY `jobs_queue_index` (`queue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `job_batches`
CREATE TABLE `job_batches` (
    `id` VARCHAR(255) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `total_jobs` INT(11) NOT NULL,
    `pending_jobs` INT(11) NOT NULL,
    `failed_jobs` INT(11) NOT NULL,
    `failed_job_ids` LONGTEXT NOT NULL,
    `options` MEDIUMTEXT,
    `cancelled_at` INT(11) DEFAULT NULL,
    `created_at` INT(11) NOT NULL,
    `finished_at` INT(11) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `migrations`
CREATE TABLE `migrations` (
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `migration` VARCHAR(255) NOT NULL,
    `batch` INT(11) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `password_reset_tokens`
CREATE TABLE `password_reset_tokens` (
    `email` VARCHAR(255) NOT NULL,
    `token` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table structure for table `personal_access_tokens`
CREATE TABLE `personal_access_tokens` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `tokenable_type` VARCHAR(255) NOT NULL,
    `tokenable_id` BIGINT(20) UNSIGNED NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `token` VARCHAR(64) NOT NULL UNIQUE,
    `abilities` TEXT,
    `last_used_at` TIMESTAMP NULL DEFAULT NULL,
    `expires_at` TIMESTAMP NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`, `tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Indexes
CREATE INDEX `idx_kelas_dosen1` ON `kelas` (`nip_dosen_1`);
CREATE INDEX `idx_kelas_dosen2` ON `kelas` (`nip_dosen_2`);
CREATE INDEX `idx_kelaskm_dosen1` ON `kelaskm` (`nip_dosen_1`);
CREATE INDEX `idx_kelaskm_dosen2` ON `kelaskm` (`nip_dosen_2`);
CREATE INDEX `idx_krs_matakuliah` ON `krs` (`program_studi_pengampu`, `kurikulum`, `kode_matakuliah`);
CREATE INDEX `idx_krskm_matakuliah` ON `krskm` (`program_studi_pengampu`, `kurikulum`, `kode_matakuliah`);
CREATE INDEX `idx_nilaipindahan_nim` ON `nilaipindahan` (`nim`);
CREATE INDEX `idx_perwalian_prodi` ON `perwalian` (`prodi`);
CREATE INDEX `idx_proporsinilai_nim` ON `proporsinilai` (`nim`);
CREATE INDEX `idx_tagihan_nim` ON `tagihan` (`nim`);
CREATE INDEX `idx_registrations_mobile_number` ON `registrations` (`mobile_number`);
CREATE INDEX `idx_registrations_email` ON `registrations` (`email`);
CREATE INDEX `idx_registrations_registration_status` ON `registrations` (`registration_status`);
CREATE INDEX `idx_registrations_payment_status` ON `registrations` (`payment_status`);

COMMIT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;